🍱asset:
- changed-files:
  - any-glob-to-any-file: ['**/*.avif', '**/*.ico', '**/*.png', '**/*.svg']
♻️ci:
- changed-files:
  - any-glob-to-any-file: '.github/**/*.yml'
⚙️config:
- changed-files:
  - any-glob-to-any-file: '*config.*'
dependencies:
- changed-files:
  - any-glob-to-any-file: ['bun.lock', 'package.json']
docker:
- changed-files:
  - any-glob-to-any-file: ['.dockerignore', 'Dockerfile']
📝documentation:
- changed-files:
  - any-glob-to-any-file: ['**/*.md']
🚀enhancement:
- all:
  - changed-files:
    - any-glob-to-any-file: 'app/**'
    - all-globs-to-all-files: '!app/**/*.test.tsx'
🪸git:
- changed-files:
  - any-glob-to-any-file: ['.gitattributes', '.gitignore']
🧰infrastructure:
- changed-files:
  - any-glob-to-any-file: ['.devcontainer/*', '.editorconfig', 'biome.json']
💧drizzle:
- changed-files:
  - any-glob-to-any-file: ['app/lib/schema.ts', 'drizzle.config.ts']
✅test:
- changed-files:
  - any-glob-to-any-file: ['happydom.tsx', 'test/**']
🆚vscode:
- changed-files:
  - any-glob-to-any-file: '.vscode/*'
