import { existsSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"
import { CreateBucketCommand, S3Client } from "@aws-sdk/client-s3"
import { $ } from "bun"

const ENV_FILE_PATH = resolve(import.meta.dirname, "..", ".env")

const ENV_CONTENT = `# .env - Local development (auto-generated by scripts/dev-up.ts)
DATABASE_URL=postgres://dcrs:dcrs@localhost:5432/dcrs
DB_TYPE=postgres
BETTER_AUTH_SECRET=local-dev-secret-key-change-in-production
BETTER_AUTH_URL=http://localhost:3000
S3_ACCESS_KEY_ID=rustfs
S3_SECRET_ACCESS_KEY=rustfs123
S3_REGION=us-east-1
S3_BUCKET=dcrs-dev
S3_ENDPOINT=http://localhost:9000
`

export function generateEnvFile(): void {
  if (existsSync(ENV_FILE_PATH)) {
    console.log(
      `ℹ️ Skipping .env generation: ${ENV_FILE_PATH} already exists. ` +
        `Delete it to regenerate the default file.`,
    )
    return
  }
  writeFileSync(ENV_FILE_PATH, ENV_CONTENT)
  console.log(`✅ Generated ${ENV_FILE_PATH}`)
}

export async function createBucketIfNotExists(
  s3Client: S3Client,
  bucket: string,
): Promise<void> {
  try {
    await s3Client.send(new CreateBucketCommand({ Bucket: bucket }))
    console.log(`✅ Created bucket: ${bucket}`)
  } catch (error: unknown) {
    if (error instanceof Error && error.name === "BucketAlreadyOwnedByYou") {
      console.log(`✅ Bucket already exists: ${bucket}`)
      return
    }
    throw error
  }
}

async function main(): Promise<void> {
  generateEnvFile()

  try {
    await $`docker compose up -d --wait`
  } catch {
    console.error("❌ Failed to start Docker Compose. Is Docker running?")
    process.exit(1)
  }

  await $`bun run migrate`

  const s3Client = new S3Client({
    credentials: {
      accessKeyId: "rustfs",
      secretAccessKey: "rustfs123",
    },
    region: "us-east-1",
    endpoint: "http://localhost:9000",
    forcePathStyle: true,
  })

  await createBucketIfNotExists(s3Client, "dcrs-dev")
}

if (import.meta.main) {
  main()
}
