name: 🗑️ Cleanup caches by a branch

on:
  pull_request_target:
    paths:
      - "app/**"
      - "public/**"
      - "test/**"
      - ".dockerignore"
      - "bun.lock"
      - "Dockerfile"
      - "package.json"
      - "proxy.ts"
      - "*config.*"
    types:
      - closed

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: 🗑️ Cleanup
        env:
          GH_TOKEN: ${{ github.token }}
          REF: refs/pull/${{ github.event.pull_request.number }}/merge
          REPO: ${{ github.repository }}
        run: gh cache delete --all --ref "$REF" --repo "$REPO" --succeed-on-no-caches
