name: 💬 Comment on the pull request

on:
  workflow_call:
    inputs:
      comment:
        description: "Comment to add to the pull request"
        required: true
        type: string
      is_success:
        description: "Indicates if the previous job succeeded"
        required: true
        type: boolean
      title:
        description: "Pull request title"
        required: true
        type: string

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: 💬 Add a comment
        uses: actions/github-script@v7
        env:
          COMMENT: ${{ inputs.comment }}
          IS_SUCCESS: ${{ inputs.is_success }}
          TITLE: ${{ inputs.title }}
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const oldComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes(process.env.TITLE)
            })
            if (oldComment) {
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: oldComment.id,
              })
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: process.env.COMMENT
              })
              return
            }
            if (process.env.IS_SUCCESS === 'false') {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: process.env.COMMENT
              })
            }
